---
git_email: "shrijal.acharya@gmail.com"
git_name: "Shrijal Acharya"

ansible_user: "shricodev"

dotfiles_repo: "https://github.com/shricodev/dotfiles.git"

timezone: "Asia/Kathmandu"
keyboard_layout: "us"

needs_ssh_setup: false
