---
- name: Ensure fish shell is installed
  become: true
  ansible.builtin.package:
    name: fish
    state: present

- name: Get fish shell path
  # This below approach is supposed to be better, but somehow it gives linting
  # error with ansible-lint, so using the 'which <command>' approach for now.
  # ansible.builtin.shell: "command -v fish"
  ansible.builtin.command: "which fish"
  register: fish_path
  changed_when: false

- name: Set fish as default shell for the user
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: "{{ fish_path.stdout }}"
  when: fish_path.stdout is defined

- name: Create the '$HOME/.config/fish' directory if not exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/fish"
    mode: "0755"
    state: directory

- name: Create symlink of files to '$HOME/.config/fish' directory
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/fish"
    state: link
    force: true
