---
homelabs:
  hosts:
    homelab_ubuntu_azure:
      ansible_host: 20.119.85.208
      apache_package: apache2
      apache_php_package: libapache2-mod-php
# local:
#   hosts:
#     localhost:
#       ansible_connection: local
