return {}
-- return {
--   "jackMort/ChatGPT.nvim",
--   event = "VeryLazy",
--   dependencies = {
--     "MunifTanjim/nui.nvim",
--     "nvim-lua/plenary.nvim",
--     "nvim-telescope/telescope.nvim",
--   },
--   config = function()
--     require("chatgpt").setup({
--       api_key_cmd = "pass show site/openai/apikey",
--        edit_with_instructions = {
-- diff = false,
--   keymaps = {
--     accept = "<C-y>",
--     toggle_diff = "<C-d>",
--     toggle_settings = "<C-o>",
--     cycle_windows = "<Tab>",
--     use_output_as_input = "<C-a>",
--   },
-- },
--     })
--   end,
-- }
