return {}
-- TODO: I have not figured out a good keybinding for this plugin yet and it collides with leap.nvim. I will come back to it later.
-- return {
--   'gbprod/substitute.nvim',
--   event = { 'BufReadPre', 'BufNewFile' },
--   config = function()
--     local substitute = require 'substitute'
--
--     substitute.setup()
--
--     -- set keymaps
--     local keymap = vim.keymap -- for conciseness
--
--     keymap.set('n', 's', substitute.operator, { desc = 'Substitute with motion' })
--     keymap.set('n', 'ss', substitute.line, { desc = 'Substitute line' })
--     keymap.set('n', 'S', substitute.eol, { desc = 'Substitute to end of line' })
--     keymap.set('x', 's', substitute.visual, { desc = 'Substitute in visual mode' })
--   end,
-- }
