return {}
-- return {
--   'folke/flash.nvim',
--   event = { 'BufReadPre', 'BufNewFile' },
--   enabled = false,
--   ---@type Flash.Config
--   opts = {},
--   -- stylua: ignore
--   keys = {
--     { "s", mode = { "n", "x", "o" }, function() require("flash").jump() end, desc = "[Flash]: Jump word" },
--     -- { "S", mode = { "n", "o" }, function() require("flash").treesitter() end, desc = "[Flash]: Treesitter" },
--     { "r", mode = "o", function() require("flash").remote() end, desc = "[Flash]: Remote Flash" },
--     { "R", mode = { "o", "x" }, function() require("flash").treesitter_search() end, desc = "[Flash]: Treesitter Search" },
--     { "<c-s>", mode = { "c" }, function() require("flash").toggle() end, desc = "[Flash]: Toggle Flash Search" },
--   },
-- }
