# Make it look more like robby russel theme
add_newline = false
format = """
$character\
$directory\
$git_branch\
$python\
$cmd_duration\
${custom.dirty}\
"""

[character]
success_symbol = "[󰜴](blue)"
error_symbol = "[󰜴](red)"
vimcmd_symbol = "[󰜴](green)"

[directory]
truncation_length = 3
truncation_symbol = ""
truncate_to_repo = true
read_only = " 🔒"

[git_status]
disabled = true

[custom.dirty]
when = 'git diff-index --quiet HEAD -- 2>/dev/null; test $? -ne 0'
symbol = '✘'
style = 'yellow bold'
format = '[$symbol]($style) '
shell = ['zsh', '-f']

[git_branch]
symbol = "[git:](blue)"
disabled = false
format = '[$symbol\($branch\)](bold red) '

[cmd_duration]
min_time = 5_000
format = '[$duration](bold yellow) '

[python]
format = "[($virtualenv )](bold yellow)"
