# Make it look more like robby russel theme
add_newline = false
format = """
$character\
$directory\
$git_branch\
$git_state\
$python\
$cmd_duration\
$git_status\
"""

[character]
success_symbol = "[󰜴](blue)"
error_symbol = "[󰜴](red)"
vimcmd_symbol = "[󰜴](green)"

[directory]
truncation_length = 3
truncation_symbol = ""
truncate_to_repo = true
read_only = " 🔒"

[git_branch]
symbol = "[git:](blue)"
disabled = false
format = '[$symbol\($branch\)](bold red) '

[git_status]
disabled = false
# format = '[$all_status$ahead_behind](yellow bold) '
# untracked = "✘"
# modified = "✘"
# staged = "✘"
# renamed = ""
# deleted = ""
# conflicted = ""
# ahead = ""
# behind = ""
# diverged = "󰦻"
# stashed = ""

[cmd_duration]
min_time = 5_000
format = '[$duration](bold yellow) '

[git_state]
disabled = false

[python]
format = "[($virtualenv )](bold yellow)"

# [custom.git_status_simplified]
# when = 'test -n "$(git status --porcelain)"'
# symbol = '✘'
# style = 'yellow bold'
# format = '[$symbol]($style) '
# changing it to something else like fish causes a lot of slowness
# let it stay bash
# shell = [ 'bash' ]
