---
- name: Install ghostty
  become: true
  community.general.pacman:
    name: ghostty
    state: present

- name: Create the '$HOME/.config/ghostty' directory if not exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/ghostty"
    mode: "0755"
    state: directory

- name: Create symlink of files to '$HOME/.config/ghostty' directory
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/ghostty"
    state: link
    force: true
