---
# TODO: Currently, there's no official ubuntu package for ghostty and either you
# download or install community packages. I don't prefer installing community
# packages for ubuntu. So, leaving this for now and come back later once it's
# available for ubuntu officially.
