---
- name: Include distro specific variables
  ansible.builtin.include_vars: "{{ distro_name }}.yml"

- name: Install common packages
  become: true
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present
