---
- name: Remove unofficial docker packages if any
  become: true
  ansible.builtin.apt:
    # Refer here:
    # https://docs.docker.com/engine/install/ubuntu/#uninstall-old-versions
    name:
      - docker.io
      - docker-compose
      - docker-compose-v2
      - docker-doc
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Install docker dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Ensure /etc/apt/keyrings directory exists
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add docker's official GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Get system architecture
  ansible.builtin.command: "dpkg --print-architecture"
  register: system_arch
  changed_when: false
  failed_when: false

- name: Add docker's stable repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ system_arch.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    mode: "0644"

- name: Install docker engine
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Enable the docker service
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Add user to the 'docker' group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    append: true
    groups: docker
