---
- name: Ubuntu | Add sudo privilege to user
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: sudo
  when: ansible_distribution == "Ubuntu"

- name: Arch | Add sudo privilege to user
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: wheel
  when: ansible_distribution == "Archlinux"
