---
- name: Ensure the '.ssh' directory exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Ensure the '.ssh/authorized_keys' file exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
    state: touch
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"

- name: Set public key path
  set_fact:
    pubkey_path: "/home/{{ ansible_user }}/.ssh/{{ ansible_ssh_key_name }}.pub"

- name: Copy SSH public key to authorized_keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', pubkey_path) }}"
