---
- name: Create the '$HOME/.ssh' directory if not exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
