---
- name: Ubuntu | Ensure ansible user exists
  become: true
  ansible.builtin.user:
    name: ansible
    groups: sudo
    shell: /bin/bash
    create_home: false
  when: ansible_distribution == "Ubuntu"

- name: Arch | Ensure ansible user exists
  become: true
  ansible.builtin.user:
    name: ansible
    groups: wheel
    shell: /bin/bash
    create_home: false
  when: ansible_distribution == "Archlinux"
