---
- name: Ensure nvim is installed
  become: true
  ansible.builtin.package:
    name: neovim
    state: present

- name: Create the '$HOME/.config/nvim' directory if not exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    mode: "0755"
    state: directory

- name: Create symlink of files to '$HOME/.config/nvim' directory
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true
